### ISSUE TITLE
Register datasets in NDE dataset register

### ISSUE THREAD

**Issue by GertjanFi** [colonial-heritage/dataset-browser#62]
On 23rd Feb, @sdevalk and @Sabachi worked out the following approach to present a MWE at the workshop on 24th Feb.

1. Make a MWE trig file with associations from NMVW as an example.
2. This is basically a John doe file which will be written down properly later on. 
3. The John doe trig file has to be accepted by NDE. 
4. When this John doe trig file is accepted by NDE then this ticket has been done and delivered.
5. Within Triply discuss how to set up this metadata file as part of a pipeline. This is to be done later in another ticket.

**Comment by Sabachi** [comment]
@sdevalk and @Sabachi have validated and submitted the John doe dataset in the NDE dataset register. 
I am going to move the ticket to done.
